package ar.edu.unsta.robotteam.hexabot.view;

/**
 *
 * @author Laboratorio de Robótica / Facultad de Ingeniería / UNSTA
 */
public class JVistaPata extends javax.swing.JPanel {

    private JVistaPataLateral m_pataLateral;
    private JVistaPataSuperior m_pataSuperior;

    /**
     * Creates new form JVistaPata
     */
    public JVistaPata() {
        initComponents();

        m_pataLateral = new JVistaPataLateral();
        m_pataSuperior = new JVistaPataSuperior();

        add(m_pataLateral);
        add(m_pataSuperior);

    }

    /**
     *
     * @param p_angCoxa
     * @param p_angFemur
     * @param p_angTibia
     */
    public void setAngulos(double p_angCoxa, double p_angFemur,
            double p_angTibia) {
        m_pataLateral.setAngulos(p_angCoxa, p_angFemur, p_angTibia);
        m_pataSuperior.setAngulos(p_angCoxa, p_angFemur, p_angTibia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 2, 4, 4));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
