package ar.edu.unsta.robotteam.scene3d.test;

import ar.edu.unsta.robotteam.scene3d.Scene3DModel;
import ar.edu.unsta.robotteam.scene3d.Scene3DView;
import ar.edu.unsta.robotteam.scene3d.projector.IsometricProjector;
import ar.edu.unsta.robotteam.scene3d.projector.ObliqueProjector;
import ar.edu.unsta.robotteam.scene3d.projector.Projector;
import ar.edu.unsta.robotteam.scene3d.projector.XYProjector;
import ar.edu.unsta.robotteam.scene3d.projector.XZProjector;
import java.awt.Color;
import java.awt.Point;

/**
 *
 * @author gustavo
 */
public class Test1 extends javax.swing.JFrame {

    private Scene3DModel m_model;
    private Scene3DView m_view1;
    private Scene3DView m_view2;
    private Scene3DView m_view3;
    private Scene3DView m_view4;

    /**
     * Creates new form Test1
     */
    public Test1() {
        initComponents();

        m_model = new Scene3DModel();

        m_view1 = new Scene3DView(m_model);
        m_view2 = new Scene3DView(m_model);
        m_view3 = new Scene3DView(m_model);
        m_view4 = new Scene3DView(m_model);

        Projector m_proj1 = new XYProjector(m_view1);
        Projector m_proj2 = new XZProjector(m_view2);
        Projector m_proj3 = new ObliqueProjector(m_view3);
        Projector m_proj4 = new IsometricProjector(m_view4);

        m_view1.setProjector(m_proj1);
        m_view2.setProjector(m_proj2);
        m_view3.setProjector(m_proj3);
        m_view4.setProjector(m_proj4);

        ui_pnlCenter.add(m_view1);
        ui_pnlCenter.add(m_view2);
        ui_pnlCenter.add(m_view3);
        ui_pnlCenter.add(m_view4);

        m_view1.setScale(0.3);
        m_view2.setScale(m_view1.getScale());
        m_view3.setScale(m_view1.getScale());
        m_view4.setScale(m_view1.getScale());

        // Agrega la grilla del piso
        int l_gridWidth = 1000;
        int l_height = -250;
        for (int l_y = -l_gridWidth; l_y <= l_gridWidth; l_y += 50) {
            m_model.addPoint("GR_Y" + l_y + "_A", -l_gridWidth, l_y, l_height);
            m_model.addPoint("GR_Y" + l_y + "_B", l_gridWidth, l_y, l_height);
            m_model.addSegment("GR_Y" + l_y + "_A", "GR_Y" + l_y + "_B",
                    Color.darkGray, 1);
        } // end for
        for (int l_x = -l_gridWidth; l_x <= l_gridWidth; l_x += 50) {
            m_model.addPoint("GR_X" + l_x + "_A", l_x, -l_gridWidth, l_height);
            m_model.addPoint("GR_X" + l_x + "_B", l_x, l_gridWidth, l_height);
            m_model.addSegment("GR_X" + l_x + "_A", "GR_X" + l_x + "_B",
                    Color.darkGray, 1);
        } // end for
        // Agrega el sistema de coordenadas
        m_model.addPoint("O", 0, 0, 0);
        m_model.addPoint("VERSOR_X", 1000.0, 0, 0);
        m_model.addPoint("VERSOR_Y", 0, 1000.0, 0);
        m_model.addPoint("VERSOR_Z", 0, 0, 1000.0);

        m_model.addSegment("O", "VERSOR_X", Color.RED, 1);
        m_model.addSegment("O", "VERSOR_Y", Color.GREEN, 1);
        m_model.addSegment("O", "VERSOR_Z", Color.BLUE, 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_pnlNorth = new javax.swing.JPanel();
        ui_pnlCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().add(ui_pnlNorth, java.awt.BorderLayout.NORTH);

        ui_pnlCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        ui_pnlCenter.setLayout(new java.awt.GridLayout(2, 2, 10, 10));
        getContentPane().add(ui_pnlCenter, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(400, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        Point l_newOrigin = new Point(m_view1.getWidth() / 2, m_view1.
                getHeight() / 2);
        
        m_view1.setOrigin(l_newOrigin);
        m_view2.setOrigin(l_newOrigin);
        m_view3.setOrigin(l_newOrigin);
        m_view4.setOrigin(l_newOrigin);
        
        double l_newScale = m_view1.getWidth() / 5000.0;
        m_view1.setScale(l_newScale);
        m_view2.setScale(l_newScale);
        m_view3.setScale(l_newScale);
        m_view4.setScale(l_newScale);
        
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ui_pnlCenter;
    private javax.swing.JPanel ui_pnlNorth;
    // End of variables declaration//GEN-END:variables
}
