package ar.edu.unsta.robotteam.hexabot.test;

import ar.edu.unsta.robotteam.hexabot.util.ClientServerPort;
import ar.edu.unsta.robotteam.hexabot.util.HexaUtils;
import ar.edu.unsta.robotteam.hexabot.view.Tracer;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;

/**
 *
 * @author Laboratorio de Robótica / Facultad de Ingeniería / UNSTA
 */
public class CommTest extends javax.swing.JFrame implements Tracer {

    private ClientServerPort m_arduino1;
    private ClientServerPort m_arduino2;
    private ClientServerPort m_arduino3;

    ControlPataPanel m_pata1;
    ControlPataPanel m_pata2;
    ControlPataPanel m_pata3;
    ControlPataPanel m_pata4;
    ControlPataPanel m_pata5;
    ControlPataPanel m_pata6;

    /**
     * Creates new form CommTest
     */
    public CommTest() {
        initComponents();

        // Monitores inferiores
        ui_pnlSouth.add(new MotorMonitorPanel("ARD-1"));
        ui_pnlSouth.add(new MotorMonitorPanel("ARD-2"));
        ui_pnlSouth.add(new MotorMonitorPanel("ARD-3"));

        // Controles de patas
        m_pata1 = new ControlPataPanel(1);
        m_pata2 = new ControlPataPanel(2);
        m_pata3 = new ControlPataPanel(3);
        m_pata4 = new ControlPataPanel(4);
        m_pata5 = new ControlPataPanel(5);
        m_pata6 = new ControlPataPanel(6);

        ui_pnlControl.add(new JLabel(""));
        ui_pnlControl.add(m_pata1);
        ui_pnlControl.add(new JLabel(""));

        ui_pnlControl.add(m_pata6);
        ui_pnlControl.add(new JLabel(""));
        ui_pnlControl.add(m_pata2);

        ui_pnlControl.add(m_pata5);
        ui_pnlControl.add(new JLabel(""));
        ui_pnlControl.add(m_pata3);

        ui_pnlControl.add(new JLabel(""));
        ui_pnlControl.add(m_pata4);
        ui_pnlControl.add(new JLabel(""));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_pnlNorth = new javax.swing.JPanel();
        ui_cmdDiscover = new javax.swing.JButton();
        ui_cmdConfigure = new javax.swing.JButton();
        ui_cmdInit = new javax.swing.JButton();
        ui_cmdClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ui_cmdPIDOn = new javax.swing.JButton();
        ui_cmdPIDOff = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ui_txtSendCommand1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ui_txtSendCommand2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ui_txtSendCommand3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ui_cmdPrg1 = new javax.swing.JButton();
        ui_cmdPrg2 = new javax.swing.JButton();
        ui_cmdPrg3 = new javax.swing.JButton();
        ui_cmdPrg4 = new javax.swing.JButton();
        ui_cmdClose = new javax.swing.JButton();
        ui_pnlSouth = new javax.swing.JPanel();
        ui_pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ui_txtTrace = new javax.swing.JTextPane();
        ui_pnlControl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HEXABOT - CommTest");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ui_cmdDiscover.setText("Discover");
        ui_cmdDiscover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdDiscoverActionPerformed(evt);
            }
        });
        ui_pnlNorth.add(ui_cmdDiscover);

        ui_cmdConfigure.setText("Configure");
        ui_cmdConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdConfigureActionPerformed(evt);
            }
        });
        ui_pnlNorth.add(ui_cmdConfigure);

        ui_cmdInit.setText("Init");
        ui_cmdInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdInitActionPerformed(evt);
            }
        });
        ui_pnlNorth.add(ui_cmdInit);

        ui_cmdClear.setText("Clear");
        ui_cmdClear.setToolTipText("");
        ui_cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdClearActionPerformed(evt);
            }
        });
        ui_pnlNorth.add(ui_cmdClear);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 6));

        ui_cmdPIDOn.setText("PID On");
        ui_cmdPIDOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdPIDOnActionPerformed(evt);
            }
        });
        jPanel2.add(ui_cmdPIDOn);

        ui_cmdPIDOff.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ui_cmdPIDOff.setForeground(new java.awt.Color(255, 51, 0));
        ui_cmdPIDOff.setText("PID Off / HALT");
        ui_cmdPIDOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdPIDOffActionPerformed(evt);
            }
        });
        jPanel2.add(ui_cmdPIDOff);

        ui_pnlNorth.add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Send 1:");
        jPanel1.add(jLabel1);

        ui_txtSendCommand1.setPreferredSize(new java.awt.Dimension(100, 19));
        ui_txtSendCommand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_txtSendCommand1ActionPerformed(evt);
            }
        });
        jPanel1.add(ui_txtSendCommand1);

        jLabel2.setText("Send 2:");
        jPanel1.add(jLabel2);

        ui_txtSendCommand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_txtSendCommand2ActionPerformed(evt);
            }
        });
        jPanel1.add(ui_txtSendCommand2);

        jLabel3.setText("Send 3:");
        jPanel1.add(jLabel3);

        ui_txtSendCommand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_txtSendCommand3ActionPerformed(evt);
            }
        });
        jPanel1.add(ui_txtSendCommand3);

        ui_pnlNorth.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 4, 4));

        ui_cmdPrg1.setText("PRG1");
        ui_cmdPrg1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ui_cmdPrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdPrg1ActionPerformed(evt);
            }
        });
        jPanel3.add(ui_cmdPrg1);

        ui_cmdPrg2.setText("PRG2");
        ui_cmdPrg2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel3.add(ui_cmdPrg2);

        ui_cmdPrg3.setText("PRG3");
        ui_cmdPrg3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel3.add(ui_cmdPrg3);

        ui_cmdPrg4.setText("PRG4");
        ui_cmdPrg4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel3.add(ui_cmdPrg4);

        ui_pnlNorth.add(jPanel3);

        ui_cmdClose.setText("Close");
        ui_cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdCloseActionPerformed(evt);
            }
        });
        ui_pnlNorth.add(ui_cmdClose);

        getContentPane().add(ui_pnlNorth, java.awt.BorderLayout.PAGE_START);

        ui_pnlSouth.setLayout(new java.awt.GridLayout(3, 1, 10, 10));
        getContentPane().add(ui_pnlSouth, java.awt.BorderLayout.PAGE_END);

        ui_pnlCenter.setLayout(new java.awt.GridLayout(1, 2));

        ui_txtTrace.setEditable(false);
        ui_txtTrace.setBackground(new java.awt.Color(102, 102, 102));
        ui_txtTrace.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        ui_txtTrace.setForeground(new java.awt.Color(0, 204, 0));
        ui_txtTrace.setText("???");
        jScrollPane1.setViewportView(ui_txtTrace);

        ui_pnlCenter.add(jScrollPane1);

        ui_pnlControl.setLayout(new java.awt.GridLayout(4, 3));
        ui_pnlCenter.add(ui_pnlControl);

        getContentPane().add(ui_pnlCenter, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(985, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void trace(Throwable p_ex) {
        trace(p_ex.getMessage());
    }

    private void ui_cmdDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdDiscoverActionPerformed
        doDiscover();
    }//GEN-LAST:event_ui_cmdDiscoverActionPerformed

    private void ui_cmdConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdConfigureActionPerformed
        doConfigure();
    }//GEN-LAST:event_ui_cmdConfigureActionPerformed

    private void ui_cmdInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdInitActionPerformed
        doInit();
    }//GEN-LAST:event_ui_cmdInitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        doCloseAll();
    }//GEN-LAST:event_formWindowClosing

    private void ui_cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdClearActionPerformed
        ui_txtTrace.setText("");
    }//GEN-LAST:event_ui_cmdClearActionPerformed

    private void ui_cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdCloseActionPerformed
        doCloseAll();
    }//GEN-LAST:event_ui_cmdCloseActionPerformed

    private void ui_txtSendCommand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_txtSendCommand1ActionPerformed
        doSend(1);
    }//GEN-LAST:event_ui_txtSendCommand1ActionPerformed

    private void ui_txtSendCommand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_txtSendCommand2ActionPerformed
        doSend(2);
    }//GEN-LAST:event_ui_txtSendCommand2ActionPerformed

    private void ui_txtSendCommand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_txtSendCommand3ActionPerformed
        doSend(3);
    }//GEN-LAST:event_ui_txtSendCommand3ActionPerformed

    private void ui_cmdPIDOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdPIDOnActionPerformed
        doPIDOn();
    }//GEN-LAST:event_ui_cmdPIDOnActionPerformed

    private void ui_cmdPIDOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdPIDOffActionPerformed
        doPIDOff();
    }//GEN-LAST:event_ui_cmdPIDOffActionPerformed

    private void ui_cmdPrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdPrg1ActionPerformed

        new Thread() {
            @Override
            public void run() {
                try {

                    m_arduino1.sendCommandWaitResponse("P", null);
                    m_arduino2.sendCommandWaitResponse("P", null);
                    m_arduino3.sendCommandWaitResponse("P", null);

                    int l_spCoxa = 2000;

                    m_arduino1.sendCommandWaitResponse("S", 1, l_spCoxa);
                    m_arduino1.sendCommandWaitResponse("S", 2, l_spCoxa);
                    m_arduino1.sendCommandWaitResponse("S", 3, l_spCoxa);
                    m_arduino1.sendCommandWaitResponse("S", 4, l_spCoxa);
                    m_arduino1.sendCommandWaitResponse("S", 5, l_spCoxa);
                    m_arduino1.sendCommandWaitResponse("S", 6, l_spCoxa);

                    Thread.sleep(2000);

                    int l_spFemur = 300;
                    int l_spTibia = 350;
                    m_arduino2.sendCommandWaitResponse("S", 1, l_spFemur);
                    m_arduino2.sendCommandWaitResponse("S", 3, l_spFemur);
                    m_arduino2.sendCommandWaitResponse("S", 5, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 1, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 3, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 5, l_spFemur);

                    Thread.sleep(2000);

                    m_arduino2.sendCommandWaitResponse("S", 2, l_spTibia);
                    m_arduino2.sendCommandWaitResponse("S", 4, l_spTibia);
                    m_arduino2.sendCommandWaitResponse("S", 6, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 2, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 4, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 6, l_spTibia);

                    Thread.sleep(2000);

                    l_spFemur = 600;
                    l_spTibia = 700;
                    m_arduino2.sendCommandWaitResponse("S", 1, l_spFemur);
                    m_arduino2.sendCommandWaitResponse("S", 3, l_spFemur);
                    m_arduino2.sendCommandWaitResponse("S", 5, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 1, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 3, l_spFemur);
                    m_arduino3.sendCommandWaitResponse("S", 5, l_spFemur);

                    Thread.sleep(2000);

                    m_arduino2.sendCommandWaitResponse("S", 2, l_spTibia);
                    m_arduino2.sendCommandWaitResponse("S", 4, l_spTibia);
                    m_arduino2.sendCommandWaitResponse("S", 6, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 2, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 4, l_spTibia);
                    m_arduino3.sendCommandWaitResponse("S", 6, l_spTibia);

                } catch (Exception l_ex) {
                    error(l_ex);
                }

            }
        }.start();

    }//GEN-LAST:event_ui_cmdPrg1ActionPerformed

    private void doPIDOff() {
        try {
            if (m_arduino1 != null) {
                m_arduino1.sendCommandWaitResponse("H", null);
            } // end if
            if (m_arduino2 != null) {
                m_arduino2.sendCommandWaitResponse("H", null);
            } // end if
            if (m_arduino3 != null) {
                m_arduino3.sendCommandWaitResponse("H", null);
            } // end if
        } catch (Exception l_ex) {
            error(l_ex);
        }
    }

    private void doPIDOn() {
        try {
            if (m_arduino1 != null) {
                m_arduino1.sendCommandWaitResponse("P", null);
            } // end if
            if (m_arduino2 != null) {
                m_arduino2.sendCommandWaitResponse("P", null);
            } // end if
            if (m_arduino3 != null) {
                m_arduino3.sendCommandWaitResponse("P", null);
            } // end if
        } catch (Exception l_ex) {
            error(l_ex);
        }
    }

    private void doSend(final int p_arduino) {
        new Thread() {
            @Override
            public void run() {
                try {
                    doSendSafeThread(p_arduino);
                } catch (Exception l_ex) {
                    error(l_ex);
                }

            }
        }.start();
    }

    private void doSendSafeThread(int p_arduino) throws Exception {
        String l_toSend = null;
        ClientServerPort l_port = null;
        switch (p_arduino) {
            case 1: {
                l_toSend = ui_txtSendCommand1.getText();
                l_port = m_arduino1;
            }
            break;
            case 2: {
                l_toSend = ui_txtSendCommand2.getText();
                l_port = m_arduino2;
            }
            break;
            case 3: {
                l_toSend = ui_txtSendCommand3.getText();
                l_port = m_arduino3;
            }
            break;
        }
        if (l_toSend == null) {
            return;
        } // end if

        String l_args = null;
        if (l_toSend.length() > 1) {
            l_args = l_toSend.substring(1);
            l_toSend = l_toSend.substring(0, 1);
        } // end if

        if (l_port != null) {
            l_port.sendCommandWaitResponse(l_toSend, l_args);
        } // end if
    }

    private void doCloseAll() {
        if (m_arduino1 != null) {
            m_arduino1.close();
        } // end if
        if (m_arduino2 != null) {
            m_arduino2.close();
        } // end if
        if (m_arduino3 != null) {
            m_arduino3.close();
        } // end if

        ((MotorMonitorPanel) (ui_pnlSouth.getComponent(0))).setPort(null);
        ((MotorMonitorPanel) (ui_pnlSouth.getComponent(1))).setPort(null);
        ((MotorMonitorPanel) (ui_pnlSouth.getComponent(2))).setPort(null);

    }

    private void doInit() {
        new Thread() {
            @Override
            public void run() {
                try {
                    doInitSafeThread();
                } catch (Exception l_ex) {
                    error(l_ex);
                }

            }
        }.start();
    }

    private void doInitSafeThread() throws Exception {
        trace("INIT----------------");
        initArduino(m_arduino2, "135");
        initArduino(m_arduino3, "135");
        Thread.sleep(1500);
        initArduino(m_arduino2, "246");
        initArduino(m_arduino3, "246");
        Thread.sleep(1500);
        initArduino(m_arduino1, "123456");
        Thread.sleep(1500);
    }

    private void initArduino(ClientServerPort p_arduino, String p_motors) throws
            Exception {
        if (p_arduino == null) {
            return;
        } // end if

        trace("Initizalizing Arduino...");
        for (int l_motor = 1; l_motor <= 6; l_motor++) {
            trace("Initializing motor " + l_motor);
            if (p_motors.contains(String.valueOf(l_motor))) {
                p_arduino.sendCommandWaitResponse("I", l_motor);
            } // end if
        } // end for
    }

    private void doConfigure() {
        new Thread() {
            @Override
            public void run() {
                try {
                    doConfigureSafeThread();
                } catch (Exception l_ex) {
                    error(l_ex);
                }
            }
        }.start();
    }

    private void doConfigureSafeThread() throws Exception {
        trace("CONFIGURE----------------");
        Map<Integer, Map<Integer, Integer>> l_config
                = HexaUtils.readConfig("etc/config.csv");

        for (int l_arduinoIndex : l_config.keySet()) {
            ClientServerPort l_toConfig;
            switch (l_arduinoIndex) {
                case 1: {
                    l_toConfig = m_arduino1;
                }
                break;
                case 2: {
                    l_toConfig = m_arduino2;
                }
                break;
                case 3: {
                    l_toConfig = m_arduino3;
                }
                break;
                default: {
                    throw new Exception("Invalid arduino index - "
                            + l_arduinoIndex);
                }
            }
            if (l_toConfig == null) {
                trace("Can't config arduino " + l_arduinoIndex);
                continue;
            } // end if
            Map<Integer, Integer> l_arduinoSet = l_config.get(l_arduinoIndex);
            for (int l_param : l_arduinoSet.keySet()) {
                int l_value = l_arduinoSet.get(l_param);
                l_toConfig.sendCommandWaitResponse("C", l_param + " " + l_value);

                if (l_param >= 81 && l_param <= 86) {
                    // Control de máximo valor
                    if (l_arduinoIndex == 1) {
                        // Máximo de coxas 
                        switch (l_param) {
                            case 81: {
                                m_pata1.setMaxCoxa(l_value);
                            }
                            break;
                            case 82: {
                                m_pata2.setMaxCoxa(l_value);
                            }
                            break;
                            case 83: {
                                m_pata3.setMaxCoxa(l_value);
                            }
                            break;
                            case 84: {
                                m_pata4.setMaxCoxa(l_value);
                            }
                            break;
                            case 85: {
                                m_pata5.setMaxCoxa(l_value);
                            }
                            break;
                            case 86: {
                                m_pata6.setMaxCoxa(l_value);
                            }
                            break;
                        } // end switch
                    } else if (l_arduinoIndex == 2) {
                        // Máximo de patas 1 a 3
                        switch (l_param) {
                            case 81: {
                                m_pata1.setMaxFemur(l_value);
                            }
                            break;
                            case 82: {
                                m_pata1.setMaxTibia(l_value);
                            }
                            break;
                            case 83: {
                                m_pata2.setMaxFemur(l_value);
                            }
                            break;
                            case 84: {
                                m_pata2.setMaxTibia(l_value);
                            }
                            break;
                            case 85: {
                                m_pata3.setMaxFemur(l_value);
                            }
                            break;
                            case 86: {
                                m_pata3.setMaxTibia(l_value);
                            }
                            break;
                        } // end switch
                    } else if (l_arduinoIndex == 3) {
                        // Máximo de patas 4 a 6
                        switch (l_param) {
                            case 81: {
                                m_pata4.setMaxFemur(l_value);
                            }
                            break;
                            case 82: {
                                m_pata4.setMaxTibia(l_value);
                            }
                            break;
                            case 83: {
                                m_pata5.setMaxFemur(l_value);
                            }
                            break;
                            case 84: {
                                m_pata5.setMaxTibia(l_value);
                            }
                            break;
                            case 85: {
                                m_pata6.setMaxFemur(l_value);
                            }
                            break;
                            case 86: {
                                m_pata6.setMaxTibia(l_value);
                            }
                            break;
                        } // end switch
                    } else {
                        // Comando desconocido
                    } // end if // end if // end if

                } // end if

            } // end for
        } // end for
    }

    private void doDiscover() {
        new Thread() {
            @Override
            public void run() {
                try {
                    doDiscoverSafeThread();
                } catch (Exception l_ex) {
                    error(l_ex);
                }
            }
        }.start();
    }

    private void doDiscoverSafeThread() throws Exception {

        doCloseAll();

        trace("DISCOVER----------------");
        List<String> l_ports = HexaUtils.getSerialPorts();
        for (String l_portName : l_ports) {
            ClientServerPort l_port = null;
            try {
                trace("Discovering port " + l_portName);
                l_port = new ClientServerPort(l_portName, 500, this);
                l_port.open();
                String l_response = l_port.sendCommandWaitResponse("A", null);
                trace("Response: " + l_response);
                if (l_response.equals("1")) {
                    // Arduino de coxas
                    m_arduino1 = l_port;

                    MotorMonitorPanel l_monitor
                            = (MotorMonitorPanel) (ui_pnlSouth.getComponent(0));
                    l_monitor.setPort(l_port);
                    m_pata1.setPortCoxa(l_port);
                    m_pata1.setMotorCoxa(1);
                    m_pata2.setPortCoxa(l_port);
                    m_pata2.setMotorCoxa(2);
                    m_pata3.setPortCoxa(l_port);
                    m_pata3.setMotorCoxa(3);
                    m_pata4.setPortCoxa(l_port);
                    m_pata4.setMotorCoxa(4);
                    m_pata5.setPortCoxa(l_port);
                    m_pata5.setMotorCoxa(5);
                    m_pata6.setPortCoxa(l_port);
                    m_pata6.setMotorCoxa(6);

                } else if (l_response.equals("2")) {
                    // Arduino de patas 1 a 3
                    m_arduino2 = l_port;

                    MotorMonitorPanel l_monitor
                            = (MotorMonitorPanel) (ui_pnlSouth.getComponent(1));
                    l_monitor.setPort(l_port);
                    m_pata1.setPortFemur(l_port);
                    m_pata1.setMotorFemur(1);
                    m_pata2.setPortFemur(l_port);
                    m_pata2.setMotorFemur(3);
                    m_pata3.setPortFemur(l_port);
                    m_pata3.setMotorFemur(5);
                    m_pata1.setPortTibia(l_port);
                    m_pata1.setMotorTibia(2);
                    m_pata2.setPortTibia(l_port);
                    m_pata2.setMotorTibia(4);
                    m_pata3.setPortTibia(l_port);
                    m_pata3.setMotorTibia(6);

                } else if (l_response.equals("3")) {
                    // Arduino de patas 4 a a
                    m_arduino3 = l_port;

                    MotorMonitorPanel l_monitor
                            = (MotorMonitorPanel) (ui_pnlSouth.getComponent(2));
                    l_monitor.setPort(l_port);
                    m_pata4.setPortFemur(l_port);
                    m_pata4.setMotorFemur(1);
                    m_pata5.setPortFemur(l_port);
                    m_pata5.setMotorFemur(3);
                    m_pata6.setPortFemur(l_port);
                    m_pata6.setMotorFemur(5);
                    m_pata4.setPortTibia(l_port);
                    m_pata4.setMotorTibia(2);
                    m_pata5.setPortTibia(l_port);
                    m_pata5.setMotorTibia(4);
                    m_pata6.setPortTibia(l_port);
                    m_pata6.setMotorTibia(6);

                } else {
                    l_port.close();
                    throw new Exception("Unknown Arduino identificator: "
                            + l_response);
                } // end if // end if // end if
            } catch (Exception l_ex) {
                if (l_port != null) {
                    l_port.close();
                } // end if
                trace(l_ex.getMessage());
                error(l_ex);
            }
        } // end for
    }

    private static void error(Throwable p_ex) {
        System.out.println(p_ex.getMessage());
        p_ex.printStackTrace();
    }

    public void trace(String p_msg) {
        String l_txt = ui_txtTrace.getText();
        l_txt = l_txt + "\n" + p_msg;
        if (l_txt.length() > 1000) {
            l_txt = l_txt.substring(l_txt.length() - 1000);
        } // end if
        ui_txtTrace.setText(l_txt);
        ui_txtTrace.setCaretPosition(l_txt.length());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ui_cmdClear;
    private javax.swing.JButton ui_cmdClose;
    private javax.swing.JButton ui_cmdConfigure;
    private javax.swing.JButton ui_cmdDiscover;
    private javax.swing.JButton ui_cmdInit;
    private javax.swing.JButton ui_cmdPIDOff;
    private javax.swing.JButton ui_cmdPIDOn;
    private javax.swing.JButton ui_cmdPrg1;
    private javax.swing.JButton ui_cmdPrg2;
    private javax.swing.JButton ui_cmdPrg3;
    private javax.swing.JButton ui_cmdPrg4;
    private javax.swing.JPanel ui_pnlCenter;
    private javax.swing.JPanel ui_pnlControl;
    private javax.swing.JPanel ui_pnlNorth;
    private javax.swing.JPanel ui_pnlSouth;
    private javax.swing.JTextField ui_txtSendCommand1;
    private javax.swing.JTextField ui_txtSendCommand2;
    private javax.swing.JTextField ui_txtSendCommand3;
    private javax.swing.JTextPane ui_txtTrace;
    // End of variables declaration//GEN-END:variables
}
