package ar.edu.unsta.robotteam.hexabot.test;

import ar.edu.unsta.robotteam.hexabot.view.JJoystick;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Laboratorio de Robótica / Facultad de Ingeniería / UNSTA
 */
public class JJoystickTest extends javax.swing.JFrame {

    private JJoystick m_joystick;

    /**
     * Creates new form JJoystickTest
     */
    public JJoystickTest() {
        initComponents();

        m_joystick = new JJoystick();
        getContentPane().add(m_joystick, BorderLayout.CENTER);

        // Escucha el cambio de valor
        m_joystick.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent p_evt) {
                ui_lblSpeed.setText(String.valueOf(m_joystick.getDistance()));
                ui_lblBearing.setText(String.valueOf(m_joystick.getBearing()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ui_lblSpeed = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ui_lblBearing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Speed:");
        jPanel1.add(jLabel1);

        ui_lblSpeed.setText("0");
        jPanel1.add(ui_lblSpeed);

        jLabel2.setText("Bearing:");
        jPanel1.add(jLabel2);

        ui_lblBearing.setText("0");
        jPanel1.add(ui_lblBearing);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(400, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JJoystickTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ui_lblBearing;
    private javax.swing.JLabel ui_lblSpeed;
    // End of variables declaration//GEN-END:variables
}
