package ar.edu.unsta.robotteam.hexabot.test;

import ar.edu.unsta.robotteam.hexabot.util.ClientServerPort;
import ar.edu.unsta.robotteam.hexabot.view.Tracer;

/**
 *
 */
public class PIDTest extends javax.swing.JFrame implements Tracer {

    private ClientServerPort m_port;

    /**
     * Creates new form PIDTest
     */
    public PIDTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ui_sldKP = new javax.swing.JSlider();
        ui_sldKI = new javax.swing.JSlider();
        ui_sldKD = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ui_cmdStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("PID TEST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 240, -1));

        jButton1.setText("PRG #1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 180, 50));

        ui_sldKP.setMajorTickSpacing(1000);
        ui_sldKP.setMaximum(5000);
        ui_sldKP.setMinorTickSpacing(200);
        ui_sldKP.setPaintLabels(true);
        ui_sldKP.setPaintTicks(true);
        ui_sldKP.setValue(2000);
        getContentPane().add(ui_sldKP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 540, 40));

        ui_sldKI.setMajorTickSpacing(200);
        ui_sldKI.setMaximum(2000);
        ui_sldKI.setMinorTickSpacing(100);
        ui_sldKI.setPaintLabels(true);
        ui_sldKI.setPaintTicks(true);
        ui_sldKI.setValue(150);
        getContentPane().add(ui_sldKI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 540, -1));

        ui_sldKD.setMajorTickSpacing(2000);
        ui_sldKD.setMaximum(10000);
        ui_sldKD.setMinorTickSpacing(1000);
        ui_sldKD.setPaintLabels(true);
        ui_sldKD.setPaintTicks(true);
        getContentPane().add(ui_sldKD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 540, -1));

        jLabel2.setText("kP:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("kI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setText("kD:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("/ 1000");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jLabel6.setText("/ 1000");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        jLabel7.setText("/ 1000");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        ui_cmdStop.setBackground(new java.awt.Color(255, 0, 51));
        ui_cmdStop.setForeground(new java.awt.Color(255, 255, 255));
        ui_cmdStop.setText("STOP");
        ui_cmdStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_cmdStopActionPerformed(evt);
            }
        });
        getContentPane().add(ui_cmdStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 90, 50));

        setSize(new java.awt.Dimension(723, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        doPrg1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed


    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        close();
    }//GEN-LAST:event_formWindowClosing

    private void ui_cmdStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_cmdStopActionPerformed

        close();

    }//GEN-LAST:event_ui_cmdStopActionPerformed

    private void close() {
        try {
            System.out.println("Closing");
            if (m_port != null) {
                m_port.sendCommandWaitResponse("H", null);
                m_port.close();
                m_port = null;
            } // end if
        } catch (Exception ex) {
            trace(ex);
        }
    }

    private void doPrg1() {

        Thread l_thread = new Thread() {
            @Override
            public void run() {
                System.out.println("PRG1");
                try {
                    if (m_port != null) {
                        m_port.close();
                    } // end if
                    m_port = new ClientServerPort("/dev/ttyACM0", 2000,
                            PIDTest.this);
                    m_port.open();
                    System.out.println("Port open.");

                    Thread.sleep(500);

                    m_port.sendCommandWaitResponse("A", null);

                    int l_kp = ui_sldKP.getValue();
                    int l_ki = ui_sldKI.getValue();
                    int l_kd = ui_sldKD.getValue();

                    m_port.sendCommandWaitResponse("C", 1, 23); // 1,23,1,1,1,MOT-1+,naranja,Coxa 1
                    m_port.sendCommandWaitResponse("C", 11, 12); // 11,12,1,1,1,MOT-1-,amarillo,Coxa 1
                    m_port.sendCommandWaitResponse("C", 21, 55); // 21,55,1,1,1,ENC-1,violeta,Coxa 1
                    m_port.sendCommandWaitResponse("C", 31, 54); // 31,54,1,1,1,INI-1,gris,Coxa 1            
                    m_port.sendCommandWaitResponse("C", 81, 4350); // 1,81,4350,1,1,1,MAX-1,---,Coxa 1
                    m_port.sendCommandWaitResponse("C", 91, l_kp); // 1,91,2000,1,1,1,KP-1,---,Coxa 1
                    m_port.sendCommandWaitResponse("C", 101, l_ki); // 1,101,150,1,1,1,KI-1,---,Coxa 1
                    m_port.sendCommandWaitResponse("C", 111, l_kd); // 1,111,0,1,1,1,KD-1,---,Coxa 1

                    m_port.sendCommandWaitResponse("I", 1);
                    Thread.sleep(5000);

                    m_port.sendCommandWaitResponse("P", null);

                    for (int l_count = 0; l_count < 4; l_count++) {
                        for (int l_sp = 1000; l_sp <= 4000; l_sp += 1000) {
                            m_port.sendCommandWaitResponse("S", 1, l_sp);
                            Thread.sleep(1500);
                        } // end for
                        for (int l_sp = 3000; l_sp >= 2000; l_sp -= 1000) {
                            m_port.sendCommandWaitResponse("S", 1, l_sp);
                            Thread.sleep(1500);
                        } // end for
                    }

                } catch (Exception ex) {
                    trace(ex);
                }
            }

        };

        l_thread.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIDTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton ui_cmdStop;
    private javax.swing.JSlider ui_sldKD;
    private javax.swing.JSlider ui_sldKI;
    private javax.swing.JSlider ui_sldKP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void trace(String p_msg) {
        System.out.println(p_msg);
    }

    @Override
    public void trace(Throwable p_ex) {
        System.out.println(p_ex.getMessage());
        //p_ex.printStackTrace();
    }
}
