package ar.edu.unsta.robotteam.scene3d;

import ar.edu.unsta.robotteam.scene3d.projector.Projector;
import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.util.List;

/**
 *
 * @author gustavo
 */
public class Scene3DView extends javax.swing.JPanel {

    private Point m_startDrag = null;
    private Point m_origin = new Point(100, 100);

    private boolean m_aliasing;

    /**
     * Get the value of aliasing
     *
     * @return the value of aliasing
     */
    public boolean isAliasing() {
        return m_aliasing;
    }

    /**
     * Set the value of aliasing
     *
     * @param p_aliasing new value of aliasing
     */
    public void setAliasing(boolean p_aliasing) {
        this.m_aliasing = p_aliasing;
    }

    /**
     * Get the value of origin
     *
     * @return the value of origin
     */
    public Point getOrigin() {
        return m_origin;
    }

    /**
     * Set the value of origin
     *
     * @param p_origin new value of origin
     */
    public void setOrigin(Point p_origin) {
        this.m_origin = p_origin;
    }

    private double m_scale = 100.0;

    /**
     * Get the value of scale
     *
     * @return the value of scale
     */
    public double getScale() {
        return m_scale;
    }

    /**
     * Set the value of scale
     *
     * @param p_scale new value of scale
     */
    public void setScale(double p_scale) {
        this.m_scale = p_scale;
    }

    private Scene3DModel m_model;

    private Projector m_projector;

    /**
     * Get the value of projector
     *
     * @return the value of projector
     */
    public Projector getProjector() {
        return m_projector;
    }

    /**
     * Set the value of projector
     *
     * @param p_projector new value of projector
     */
    public void setProjector(Projector p_projector) {
        this.m_projector = p_projector;
    }

    /**
     * Get the value of model
     *
     * @return the value of model
     */
    public Scene3DModel getModel() {
        return m_model;
    }

    /**
     * Set the value of model
     *
     * @param p_model new value of model
     */
    public void setModel(Scene3DModel p_model) {
        this.m_model = p_model;
    }

    /**
     * Creates new form Scene3DView
     */
    public Scene3DView(Scene3DModel p_model) {
        setModel(p_model);
        initComponents();
    }

    @Override
    public void paint(Graphics p_g) {
        super.paint(p_g);

        Graphics2D l_gr = (Graphics2D) p_g;

        l_gr.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                (m_aliasing) ? RenderingHints.VALUE_ANTIALIAS_ON
                        : RenderingHints.VALUE_ANTIALIAS_OFF);

        List<Line3DSegment> l_list = getModel().getSegments();
        for (Line3DSegment l_segment : l_list) {
            if (l_segment.getColor() != null) {
                l_gr.setColor(l_segment.getColor());
            } // end if

            if (l_segment.getWidth() != -1) {
                l_gr.setStroke(new BasicStroke(l_segment.getWidth()));
            } // end if

            Point3D l_pointA = getModel().getPoint(l_segment.getIdPointA());
            Point3D l_pointB = getModel().getPoint(l_segment.getIdPointB());

            Point l_a = m_projector.project(l_pointA);
            Point l_b = m_projector.project(l_pointB);

            l_gr.drawLine(l_a.x, l_a.y, l_b.x, l_b.y);

        } // end for 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved

        double l_factor = (evt.getWheelRotation() < 0) ? 1.2 : 0.8;
        setScale(getScale() * l_factor);

        repaint();

    }//GEN-LAST:event_formMouseWheelMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        int l_deltaX = evt.getX() - m_startDrag.x;
        int l_deltaY = evt.getY() - m_startDrag.y;
        System.out.format("delta %d,%d\n", l_deltaX, l_deltaY);
        m_origin.move(m_origin.x + l_deltaX, m_origin.y + l_deltaY);
        m_startDrag = evt.getPoint();
        repaint();

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        m_startDrag = evt.getPoint();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
