package ar.edu.unsta.robotteam.hexabot.test;

import ar.edu.unsta.robotteam.hexabot.util.ClientServerPort;

/**
 *
 * @author Laboratorio de Robótica / Facultad de Ingeniería / UNSTA
 */
public class ControlPataPanel extends javax.swing.JPanel {

    private int m_nroPata;
    private ClientServerPort m_portCoxa;
    private ClientServerPort m_portFemur;
    private ClientServerPort m_portTibia;
    private int m_motorCoxa = 0;
    private int m_motorFemur = 0;
    private int m_motorTibia = 0;

    private int m_maxCoxa = 100;
    private int m_maxFemur = 100;
    private int m_maxTibia = 100;

    /**
     *
     * @param p_port
     */
    public void setPortCoxa(ClientServerPort p_port) {
        m_portCoxa = p_port;
    }

    /**
     *
     * @param p_port
     */
    public void setPortFemur(ClientServerPort p_port) {
        m_portFemur = p_port;
    }

    /**
     *
     * @param p_port
     */
    public void setPortTibia(ClientServerPort p_port) {
        m_portTibia = p_port;
    }

    /**
     *
     * @param p_motor
     */
    public void setMotorCoxa(int p_motor) {
        m_motorCoxa = p_motor;
    }

    /**
     *
     * @param p_motor
     */
    public void setMotorFemur(int p_motor) {
        m_motorFemur = p_motor;
    }

    /**
     *
     * @param p_motor
     */
    public void setMotorTibia(int p_motor) {
        m_motorTibia = p_motor;
    }

    /**
     *
     * @param p_max
     */
    public void setMaxCoxa(int p_max) {
        m_maxCoxa = p_max;
    }

    /**
     *
     * @param p_max
     */
    public void setMaxFemur(int p_max) {
        m_maxFemur = p_max;
    }

    /**
     *
     * @param p_max
     */
    public void setMaxTibia(int p_max) {
        m_maxTibia = p_max;
    }

    /**
     * Creates new form ControlPataPanel
     *
     * @param p_nroPata
     */
    public ControlPataPanel(int p_nroPata) {
        m_nroPata = p_nroPata;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        ui_sldCoxa = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        ui_sldFemur = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        ui_sldTibia = new javax.swing.JSlider();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Coxa");
        jLabel1.setAlignmentY(0.0F);
        add(jLabel1, new java.awt.GridBagConstraints());

        ui_sldCoxa.setMajorTickSpacing(10);
        ui_sldCoxa.setMinorTickSpacing(2);
        ui_sldCoxa.setPaintLabels(true);
        ui_sldCoxa.setValue(0);
        ui_sldCoxa.setAlignmentX(0.0F);
        ui_sldCoxa.setAlignmentY(0.0F);
        ui_sldCoxa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ui_sldCoxaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ui_sldCoxa, gridBagConstraints);

        jLabel2.setText("Femur");
        jLabel2.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        ui_sldFemur.setMajorTickSpacing(10);
        ui_sldFemur.setMinorTickSpacing(2);
        ui_sldFemur.setPaintLabels(true);
        ui_sldFemur.setValue(0);
        ui_sldFemur.setAlignmentX(0.0F);
        ui_sldFemur.setAlignmentY(0.0F);
        ui_sldFemur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ui_sldFemurStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ui_sldFemur, gridBagConstraints);

        jLabel3.setText("Tibia");
        jLabel3.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);

        ui_sldTibia.setMajorTickSpacing(10);
        ui_sldTibia.setMinorTickSpacing(2);
        ui_sldTibia.setPaintLabels(true);
        ui_sldTibia.setValue(0);
        ui_sldTibia.setAlignmentX(0.0F);
        ui_sldTibia.setAlignmentY(0.0F);
        ui_sldTibia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ui_sldTibiaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ui_sldTibia, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ui_sldCoxaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ui_sldCoxaStateChanged
        fireChange(1);
    }//GEN-LAST:event_ui_sldCoxaStateChanged

    private void ui_sldFemurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ui_sldFemurStateChanged
        fireChange(2);
    }//GEN-LAST:event_ui_sldFemurStateChanged

    private void ui_sldTibiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ui_sldTibiaStateChanged
        fireChange(3);
    }//GEN-LAST:event_ui_sldTibiaStateChanged

    private void fireChange(int p_slider) {
        int l_setpoint = 0;
        ClientServerPort l_port = null;
        int l_motor = 0;
        switch (p_slider) {
            case 1: {
                // Cambio en la coxa
                l_setpoint = ui_sldCoxa.getValue() * m_maxCoxa / 100;
                l_port = m_portCoxa;
                l_motor = m_motorCoxa;
            }
            break;
            case 2: {
                // Cambio en el fémur
                l_setpoint = ui_sldFemur.getValue() * m_maxFemur / 100;
                l_port = m_portFemur;
                l_motor = m_motorFemur;
            }
            break;
            case 3: {
                // Cambio en la tibia
                l_setpoint = ui_sldTibia.getValue() * m_maxTibia / 100;
                l_port = m_portTibia;
                l_motor = m_motorTibia;
            }
            break;
        } // end switch
        try {
            l_port.sendCommandWaitResponse("S", l_motor + " " + l_setpoint);
        } catch (Exception l_ex) {
            System.out.println(l_ex.getMessage());
            l_ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider ui_sldCoxa;
    private javax.swing.JSlider ui_sldFemur;
    private javax.swing.JSlider ui_sldTibia;
    // End of variables declaration//GEN-END:variables
}
