package ar.edu.unsta.robotteam.hexabot.test;

import ar.edu.unsta.robotteam.hexabot.util.ClientServerPort;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author Laboratorio de Robótica / Facultad de Ingeniería / UNSTA
 */
public class MotorMonitorPanel extends javax.swing.JPanel {

    private ClientServerPort m_port;

    /**
     * Get the value of m_port
     *
     * @return the value of m_port
     */
    public ClientServerPort getPort() {
        return m_port;
    }

    /**
     * Set the value of m_port
     *
     * @param p_port new value of m_port
     */
    public void setPort(ClientServerPort p_port) {
        this.m_port = p_port;
        if (m_port == null) {
            ui_lblM1.setText("????");
            ui_lblM2.setText("????");
            ui_lblM3.setText("????");
            ui_lblM4.setText("????");
            ui_lblM5.setText("????");
            ui_lblM6.setText("????");

        }

    }

    /**
     * Creates new form MotorMonitorPanel
     *
     * @param p_ident
     */
    public MotorMonitorPanel(String p_ident) {
        initComponents();
        ui_lblIdent.setText(p_ident);

        TimerTask l_task = new TimerTask() {
            @Override
            public void run() {
                updateMonitor();
            }
        };

        Timer l_timer = new Timer();
        l_timer.schedule(l_task, 1000, 1000);
    }

    private void updateMonitor() {
        if (m_port == null) {
            return;
        } // end if

        if (!ui_chkAuto.isSelected()) {
            return;
        } // end if

        try {
            String l_response = m_port.sendCommandWaitResponse("Q", null);

            String l_fields[] = l_response.split(" ");
            ui_lblM1.setText(l_fields[0]);
            ui_lblM2.setText(l_fields[1]);
            ui_lblM3.setText(l_fields[2]);
            ui_lblM4.setText(l_fields[3]);
            ui_lblM5.setText(l_fields[4]);
            ui_lblM6.setText(l_fields[5]);

        } catch (Exception l_ex) {
            System.out.println(l_ex.getMessage());
            l_ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_pnlWest = new javax.swing.JPanel();
        ui_lblIdent = new javax.swing.JLabel();
        ui_chkAuto = new javax.swing.JCheckBox();
        ui_pnlCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ui_lblM1 = new javax.swing.JLabel();
        ui_lblM2 = new javax.swing.JLabel();
        ui_lblM3 = new javax.swing.JLabel();
        ui_lblM4 = new javax.swing.JLabel();
        ui_lblM5 = new javax.swing.JLabel();
        ui_lblM6 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        ui_pnlWest.setLayout(new javax.swing.BoxLayout(ui_pnlWest, javax.swing.BoxLayout.Y_AXIS));

        ui_lblIdent.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ui_lblIdent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblIdent.setText("ARD 1");
        ui_lblIdent.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        ui_pnlWest.add(ui_lblIdent);

        ui_chkAuto.setSelected(true);
        ui_chkAuto.setText("Auto?");
        ui_pnlWest.add(ui_chkAuto);

        add(ui_pnlWest, java.awt.BorderLayout.WEST);

        ui_pnlCenter.setLayout(new java.awt.GridLayout(2, 6, 4, 4));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("M1:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M2:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("M3:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("M4:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("M5:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("M6:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_pnlCenter.add(jLabel6);

        ui_lblM1.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM1.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM1.setText("????");
        ui_lblM1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM1.setOpaque(true);
        ui_pnlCenter.add(ui_lblM1);

        ui_lblM2.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM2.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM2.setText("????");
        ui_lblM2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM2.setOpaque(true);
        ui_pnlCenter.add(ui_lblM2);

        ui_lblM3.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM3.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM3.setText("????");
        ui_lblM3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM3.setOpaque(true);
        ui_pnlCenter.add(ui_lblM3);

        ui_lblM4.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM4.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM4.setText("????");
        ui_lblM4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM4.setOpaque(true);
        ui_pnlCenter.add(ui_lblM4);

        ui_lblM5.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM5.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM5.setText("????");
        ui_lblM5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM5.setOpaque(true);
        ui_pnlCenter.add(ui_lblM5);

        ui_lblM6.setBackground(new java.awt.Color(102, 102, 102));
        ui_lblM6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ui_lblM6.setForeground(new java.awt.Color(102, 255, 0));
        ui_lblM6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui_lblM6.setText("????");
        ui_lblM6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ui_lblM6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_lblM6.setOpaque(true);
        ui_pnlCenter.add(ui_lblM6);

        add(ui_pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox ui_chkAuto;
    private javax.swing.JLabel ui_lblIdent;
    private javax.swing.JLabel ui_lblM1;
    private javax.swing.JLabel ui_lblM2;
    private javax.swing.JLabel ui_lblM3;
    private javax.swing.JLabel ui_lblM4;
    private javax.swing.JLabel ui_lblM5;
    private javax.swing.JLabel ui_lblM6;
    private javax.swing.JPanel ui_pnlCenter;
    private javax.swing.JPanel ui_pnlWest;
    // End of variables declaration//GEN-END:variables
}
